name: test2
description: CoreML Supabase GPS PDF App
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.2
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  pdf: ^3.10.7
  share_plus: ^9.0.0
  path_provider: ^2.1.2
  file_picker: ^8.0.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
